import argparse
import pandas as pd
import sys
from colorama import init, Fore, Style
from validators.syntax import SyntaxValidator
from validators.mx_check import MXValidator
from validators.disposable import DisposableValidator

init(autoreset=True)

def main():
    parser = argparse.ArgumentParser(description="Zero-Cost Email List Auditor")
    parser.add_argument("input_file", help="Path to CSV file containing emails")
    parser.add_argument("--output", default="audit_report.txt", help="Path to output report")
    args = parser.parse_args()

    print(Fore.CYAN + f"\n--- Starting Email Audit: {args.input_file} ---\n")

    # 1. Load Data
    try:
        df = pd.read_csv(args.input_file)
        # Find email column (smart guess)
        email_col = next((col for col in df.columns if 'email' in col.lower()), None)
        if not email_col:
            # Fallback to first column
            email_col = df.columns[0]
            print(Fore.YELLOW + f"[!] Could not auto-detect 'email' column. Using first column: '{email_col}'")
        else:
            print(Fore.GREEN + f"[+] Found email column: '{email_col}'")
    except Exception as e:
        print(Fore.RED + f"[x] Error reading file: {e}")
        return

    # 2. Initialize Validators
    syntax_val = SyntaxValidator()
    mx_val = MXValidator()
    disp_val = DisposableValidator()

    results = []
    stats = {
        "total": 0,
        "valid": 0,
        "invalid_syntax": 0,
        "invalid_mx": 0,
        "disposable": 0,
        "typos_fixed": 0
    }

    # 3. Process Emails
    print(f"Processing {len(df)} emails...")
    
    for idx, row in df.iterrows():
        email = str(row[email_col])
        stats["total"] += 1
        
        # Step 1: Syntax
        is_syntax_valid, suggestion, err = syntax_val.validate(email)
        if not is_syntax_valid:
            if suggestion:
                status = "Typo"
                detail = f"Did you mean {suggestion}?"
                stats["typos_fixed"] += 1
            else:
                status = "Invalid Syntax"
                detail = err
                stats["invalid_syntax"] += 1
            
            # Skip expensive MX check if syntax is bad (unless it's a typo we want to check suggestion for? No, strict MVP)
            results.append({"Email": email, "Status": status, "Detail": detail})
            continue

        # Step 2: Disposable
        is_not_disposable, err = disp_val.validate(email)
        if not is_not_disposable:
            stats["disposable"] += 1
            results.append({"Email": email, "Status": "Disposable", "Detail": "Risk: Burner Check"})
            print(Fore.YELLOW + f"   [!] Disposable: {email}")
            continue

        # Step 3: MX Record (The heavy lifter)
        # Be nice to console
        print(f"\r   Checking DNS: {email.split('@')[-1]}...", end="")
        is_mx_valid, err = mx_val.validate(email)
        if not is_mx_valid:
            stats["invalid_mx"] += 1
            results.append({"Email": email, "Status": "Dead Domain", "Detail": err})
            # print(Fore.RED + f"\n   [x] Dead Domain: {email} ({err})") # Too verbose
            continue

        # If we got here -> Valid
        stats["valid"] += 1
        results.append({"Email": email, "Status": "Valid", "Detail": "Safe to send"})

    print("\n" + Fore.GREEN + "Processing Complete.")

    # 4. Generate Report
    generate_report(stats, results, args.output)

def generate_report(stats, results, filename):
    total = stats["total"]
    if total == 0: return

    valid_pct = (stats["valid"] / total) * 100
    risk_score = 100 - valid_pct
    
    report = f"""
==================================================
EMAIL LIST HEALTH AUDIT REPORT
==================================================
Generated by: Zero-Cost Email Cleaner (MVP)

SUMMARY METRICS:
----------------
Total Emails Scanned: {total}
Valid Emails:         {stats['valid']} ({valid_pct:.1f}%)
Invalid Emails:       {total - stats['valid']}

BREAKDOWN OF ISSUES:
--------------------
[x] Dead Domains (No MX):     {stats['invalid_mx']}  <-- CRITICAL (Bounces)
[!] Disposable/Burner:        {stats['disposable']}  <-- HIGH RISK (Spam Traps)
[!] Syntax Errors:            {stats['invalid_syntax']}
[i] Typos Detected:           {stats['typos_fixed']}

RECOMMENDATION:
---------------
Your list has a Risk Score of {risk_score:.1f}/100.
"""

    if risk_score > 10:
        report += "CRITICAL: Do not send to this list without cleaning. You will block your domain.\n"
    elif risk_score > 5:
        report += "WARNING: Remove the invalid emails before sending.\n"
    else:
        report += "PASS: This list looks healthy.\n"

    report += "\nDETAILED LOG (First 50 errors):\n"
    count = 0
    for r in results:
        if r['Status'] != 'Valid':
            report += f"- {r['Email']}: {r['Status']} ({r['Detail']})\n"
            count += 1
            if count >= 50: break
            
    with open(filename, "w") as f:
        f.write(report)
        
    print(Fore.WHITE + "\n" + report)
    print(Fore.CYAN + f"Full report saved to: {filename}")

if __name__ == "__main__":
    main()
